apiVersion: v1
kind: Secret
metadata:
  name: yjkim1-s3-private-key
  annotations:
     serving.kubeflow.org/s3-endpoint: s3.us-east-1.amazonaws.com # replace with your s3 endpoint
     serving.kubeflow.org/s3-usehttps: "1" # by default 1, for testing with minio you need to set to 0
     serving.kubeflow.org/s3-verifyssl: "1" # by default 1, for testing with minio you need to set to 0
     serving.kubeflow.org/s3-region: us-east-1
type: Opaque
data:
  # echo -ne "KEY_STRING" | base64
  awsAccessKeyID: AKAKAKAKAKAKAKKA=
  awsSecretAccessKey: cVkcVkcVkcVkcVkcVkcVkcVkcVkcVkcVkcVkcVkcVk==
