apiVersion: v1
kind: Secret
metadata:
  name: azcreds
type: Opaque
data:
  AZ_CLIENT_ID: XXXX
  AZ_CLIENT_SECRET: XXXX
  AZ_SUBSCRIPTION_ID: XXXX
  AZ_TENANT_ID: XXXX
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yjkim-kube-admin-sa-gcr
  namespace: kfserving-system
secrets:
  - name: azcreds
imagePullSecrets:
  - name: yjkim-kube-admin-sa-gcr-private-key