{
 "title": "전체 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Request Count (Operation Per Second)",
   "type": "graph",
   "description": "1분간 초당 요청 값 (revision_request_count 매트릭 : The number of requests that are routed to the activator)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(revision_request_count[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Request Count by Model (Operation Per Second)",
   "type": "graph",
   "description": "1분간 model 별 초당 요청값 (revision_request_count 매트릭)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(revision_request_count[1m])) by (configuration_name), 0.001)",
     "legendFormat": "{{configuration_name}}"
    }
   ]
  },
  {
   "title": "Error Count (4xx/5xx Responses)",
   "type": "graph",
   "description": "5분간 응답 코드가 4xx/5xx인 요청 값(revision_request_count 매트릭)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(revision_request_count{response_code_class=\"5xx|4xx\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "description": "1분간 모든 컨테이너가 소비하는 누적 CPU 시간의 초당 평균 증가율 (container_cpu_usage_seconds_total 매트릭 : Cumulative CPU time consumed in seconds)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container != \"POD\", container != \"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "모든 컨테이너의 메모리 사용량 (container_memory_usage_bytes 매트릭 : Current memory usage in bytes, including all memory regardless of when it was accessed)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container != \"POD\", container != \"\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Network Usage",
   "type": "graph",
   "description": "1분간 모든 컨테이너의 네트워크 사용량 (container_network_transmit_bytes_total 매트릭 : Cumulative count of bytes transmitted, container_network_receive_bytes_total 매트릭 : Cumulative count of bytes received)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[1m])) + sum(rate(container_network_receive_bytes_total[1m]))"
    }
   ]
  }
 ]
}